apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-student-10
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: student-10
  syncPolicy:
    automated: {}
  sources:
    - repoURL: 'https://charts.bitnami.com/bitnami'
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - /jenkins/values.yaml
      chart: jenkins
    - repoURL: 'https://github.com/mathwro/argocd-kata'
      targetRevision: main
      ref: values
